data:
    path: ../../../../../../media/doha/SSK Drive/dataset/MVSEC/outdoor_night2_gt.hdf5 #datasets/data/ECD/
    mode: events # events/time/frames/gtflow_dt1/gtflow_dt4
    window: 15000 # events/time/frames/flowmaps
    window_eval: 15000 # events

# model:
#     mask_output: True
model:
    name: LIFFireNet # Specify the model name
    num_bins: 10      # Number of temporal bins
    base_num_channels: 16  # Base number of channels
    kernel_size: 3         # Kernel size for convolution
    encoding: True         # Whether to use encoding
    mask_output: True
    activations: ["relu", "relu"]
    spiking_neuron: Null

metrics:
    name: [FWL, RSAT]  # FWL, RSAT, AEE
    flow_scaling: 128 # depends on the training dataset

loader:
    batch_size: 1
    resolution: [180, 240] # H x W
    augment: []
    gpu: 0

vis:
    enabled: True
    px: 400
    bars: True
    activity: False
    store: False

hot_filter:
    enabled: True
    max_px: 100
    min_obvs: 5
    max_rate: 0.8
